build: build-linkahead-server build-linkahead-backend build-linkahead-webui

build-linkahead-webui:
	$(MAKE) -C webui docker-image

build-linkahead-backend:
	$(MAKE) -C backend docker-image

build-linkahead-server:
	$(MAKE) -C server docker-image
